let posts = [
    {
      username: "user1",
      image: "https://example.com/image1.jpg",
      date: "2024-10-28",
      caption: "Exploring the mountains!",
      likes: 150,
    },
    {
      username: "user2",
      image: "https://example.com/image2.jpg",
      date: "2024-10-27",
      caption: "Coffee and coding ☕💻",
      likes: 200,
    },
    {
      username: "user3",
      image: "https://example.com/image3.jpg",
      date: "2024-10-26",
      caption: "Sunset at the beach 🌅",
      likes: 320,
    },
    {
      username: "user4",
      image: "https://example.com/image4.jpg",
      date: "2024-10-25",
      caption: "City lights at night!",
      likes: 275,
    },
    {
      username: "user5",
      image: "https://example.com/image5.jpg",
      date: "2024-10-24",
      caption: "Nature hike 🌲🌳",
      likes: 180,
    },
    {
      username: "user6",
      image: "https://example.com/image6.jpg",
      date: "2024-10-23",
      caption: "Throwback to summer ☀️",
      likes: 145,
    },
    {
      username: "user7",
      image: "https://example.com/image7.jpg",
      date: "2024-10-22",
      caption: "Learning new recipes 🍲",
      likes: 360,
    },
    {
      username: "user8",
      image: "https://example.com/image8.jpg",
      date: "2024-10-21",
      caption: "The road less traveled 🚗",
      likes: 310,
    },
    {
      username: "user9",
      image: "https://example.com/image9.jpg",
      date: "2024-10-20",
      caption: "Weekend vibes 🎉",
      likes: 220,
    },
    {
      username: "user10",
      image: "https://example.com/image10.jpg",
      date: "2024-10-19",
      caption: "Best pizza in town 🍕",
      likes: 195,
    },
    {
      username: "user11",
      image: "https://example.com/image11.jpg",
      date: "2024-10-18",
      caption: "Morning run 🏃‍♂️",
      likes: 250,
    },
    {
      username: "user12",
      image: "https://example.com/image12.jpg",
      date: "2024-10-17",
      caption: "New art project 🎨",
      likes: 330,
    },
    {
      username: "user13",
      image: "https://example.com/image13.jpg",
      date: "2024-10-16",
      caption: "Mountain climbing adventure 🧗",
      likes: 290,
    },
    {
      username: "user14",
      image: "https://example.com/image14.jpg",
      date: "2024-10-15",
      caption: "Family time 👨‍👩‍👧‍👦",
      likes: 210,
    },
    {
      username: "user15",
      image: "https://example.com/image15.jpg",
      date: "2024-10-14",
      caption: "Cityscape photography 📸",
      likes: 305,
    },
    {
      username: "user16",
      image: "https://example.com/image16.jpg",
      date: "2024-10-13",
      caption: "Backyard garden update 🌱",
      likes: 155,
    },
    {
      username: "user17",
      image: "https://example.com/image17.jpg",
      date: "2024-10-12",
      caption: "Starting a new book 📚",
      likes: 175,
    },
    {
      username: "user18",
      image: "https://example.com/image18.jpg",
      date: "2024-10-11",
      caption: "Beautiful lake reflection 🌅",
      likes: 280,
    },
    {
      username: "user19",
      image: "https://example.com/image19.jpg",
      date: "2024-10-10",
      caption: "Chilling with friends 👥",
      likes: 265,
    },
    {
      username: "user20",
      image: "https://example.com/image20.jpg",
      date: "2024-10-09",
      caption: "Late-night coding session 🕹️",
      likes: 240,
    },
  ];

  export default posts ;